# Generated by Django 4.2.2 on 2023-06-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountstatus',
            options={'verbose_name_plural': 'Account Status'},
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='account_photos/%Y/%m/'),
        ),
    ]
